CREATE TABLE IF NOT EXISTS user (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
user_name VARCHAR(255) NOT NULL,
event_id INT,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS event (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
event_name VARCHAR(255) NOT NULL,
file_id INT,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS file (
id INT NOT NULL AUTO_INCREMENT UNIQUE,
file_name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);